### ISSUE TITLE
Why is Finegrained_GNN?

### ISSUE THREAD

**Issue by accer-iou** [HANYIIK/Finegrained_GNN#1]
Hi, I recently focus on EEG Emotion Recognition Study. I think the Fine Grained GNN is an interesting structure. May I know why is called Fine Grained and the theory details. Hope to your response.

**Comment by HANYIIK** [comment]
This is an algorithm which I’m working on for a paper, it needs to use visual interpretation to filter out unimportant nodes for a GNN model.
